### ISSUE TITLE
please  exceptions occured when using ready ui on click om pay button

### ISSUE THREAD

**Issue by Abdallah-Samman** [ahmedelkhyary/hyperpay#47]
this exception occur when using ready ui. 
java.lang.SecurityException: Settings key: <enabled_input_methods> is only readable to apps with targetSdkVersion lower than or equal to: 33
E/AndroidRuntime( 4682): 	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3514)
E/AndroidRuntime( 4682): 	at android.provider.Settings$Secure.getStringForUser(Settings.java:6921)
E/AndroidRuntime( 4682): 	at android.provider.Settings$Secure.getString(Settings.java:6887)
E/AndroidRuntime( 4682): 	at nts.ഉ.ዎ(SourceFile:1)
E/AndroidRuntime( 4682): 	at nts.ഉ.ᦝ(SourceFile:275)
E/AndroidRuntime( 4682): 	at nts.〨.initialize(SourceFile:49)
E/AndroidRuntime( 4682): 	at com.oppwa.mobile.connect.provider.threeds.v2.ThreeDS2TransactionManager.a(ThreeDS2TransactionManager.java:51)
E/AndroidRuntime( 4682): 	at com.oppwa.mobile.connect.provider.threeds.v2.ThreeDS2TransactionManager.getWarnings(ThreeDS2TransactionManager.java:8)
E/AndroidRuntime( 4682): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider.getThreeDS2Warnings(OppPaymentProvider.java:6)
E/AndroidRuntime( 4682): 	at com.oppwa.mobile.connect.checkout.dialog.BaseActivity.a(BaseActivity.java:99)
E/AndroidRuntime( 4682): 	at com.oppwa.mobile.connect.checkout.dialog.BaseActivity.a(BaseActivity.java:79)
E/AndroidRuntime( 4682): 	at com.oppwa.mobile.connect.checkout.dialog.BaseActivity.a(BaseActivity.java:65)
E/AndroidRuntime( 4682): 	at com.oppwa.mobile.connect.checkout.dialog.BaseActivity.c(BaseActivity.java:3)
E/AndroidRuntime( 4682): 	at com.oppwa.mobile.connect.checkout.dialog.BaseActivity.$r8$lambda$dG8xssUzlfsGUVTF1P39qmBvFsg(Unknown Source:0)
E/AndroidRuntime( 4682): 	at com.oppwa.mobile.connect.checkout.dialog.BaseActivity$$ExternalSyntheticLambda4.onFragmentResult(Unknown Source:2)
E/AndroidRuntime( 4682): 	at androidx.fragment.app.FragmentManager$LifecycleAwareResultListener.onFragmentResult(FragmentManager.java:267)
E/AndroidRuntime( 4682): 	at androidx.fragment.app.FragmentManager.setFragmentResult(FragmentManager.java:945)
E/AndroidRuntime( 4682): 	at com.oppwa.mobile.connect.checkout.dialog.PaymentInfoFragment.c(PaymentInfoFragment.java:9)
E/AndroidRuntime( 4682): 	at com.oppwa.mobile.connect.checkout.dialog.PaymentInfoFragment.$r8$lambda$ibu7f8RjDc_YqgendOdUAZ6Kjyg(Unknown Source:0)
E/AndroidRuntime( 4682): 	at com.oppwa.mobile.connect.checkout.dialog.PaymentInfoFragment$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
E/AndroidRuntime( 4682): 	at android.view.View.performClick(View.java:8055)
E/AndroidRuntime( 4682): 	at android.view.View.performClickInternal(View.java:8032)
E/AndroidRuntime( 4682): 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
E/AndroidRuntime( 4682): 	at android.view.View$PerformClick.run(View.java:31252)
E/AndroidRuntime( 4682): 	at android.os.Handler.handleCallback(Handler.java:959)
E/AndroidRuntime( 4682): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 4682): 	at android.os.Looper.loopOnce(Looper.java:232)
E/AndroidRuntime( 4682): 	at android.os.Looper.loop(Looper.java:317)
E/AndroidRuntime( 4682): 	at android.app.ActivityThread.main(ActivityThread.java:8674)
E/AndroidRuntime( 4682): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4682): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
E/AndroidRuntime( 4682): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by Ramsha-Farheen** [comment]
In file, android/app/build.gradle change this line:
targetSdkVersion 33
