### ISSUE TITLE
Creashed on android 14 when paynow button click

### ISSUE THREAD

**Issue by SaurabhAlmighty** [ahmedelkhyary/hyperpay#51]
this recorded video
https://github.com/user-attachments/assets/1d7e9cca-d747-4c9a-9766-0964c218aa84

my log here
E/AndroidRuntime( 9810): java.lang.SecurityException: Settings key: <enabled_input_methods> is only readable to apps with targetSdkVersion lower than or equal to: 33
E/AndroidRuntime( 9810): 	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3289)
E/AndroidRuntime( 9810): 	at android.provider.Settings$Secure.getStringForUser(Settings.java:6527)
E/AndroidRuntime( 9810): 	at android.provider.Settings$Secure.getString(Settings.java:6489)
E/AndroidRuntime( 9810): 	at nts.ഉ.ዎ(SourceFile:1)
E/AndroidRuntime( 9810): 	at nts.ഉ.ᦝ(SourceFile:275)
E/AndroidRuntime( 9810): 	at nts.〨.initialize(SourceFile:49)
E/AndroidRuntime( 9810): 	at com.oppwa.mobile.connect.provider.threeds.v2.ThreeDS2TransactionManager.a(ThreeDS2TransactionManager.java:51)
E/AndroidRuntime( 9810): 	at com.oppwa.mobile.connect.provider.threeds.v2.ThreeDS2TransactionManager.getWarnings(ThreeDS2TransactionManager.java:8)
E/AndroidRuntime( 9810): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider.getThreeDS2Warnings(OppPaymentProvider.java:6)
E/AndroidRuntime( 9810): 	at com.oppwa.mobile.connect.checkout.dialog.BaseActivity.a(BaseActivity.java:99)
E/AndroidRuntime( 9810): 	at com.oppwa.mobile.connect.checkout.dialog.BaseActivity.a(BaseActivity.java:79)
E/AndroidRuntime( 9810): 	at com.oppwa.mobile.connect.checkout.dialog.BaseActivity.a(BaseActivity.java:65)
E/AndroidRuntime( 9810): 	at com.oppwa.mobile.connect.checkout.dialog.BaseActivity.c(BaseActivity.java:3)
E/AndroidRuntime( 9810): 	at com.oppwa.mobile.connect.checkout.dialog.BaseActivity.$r8$lambda$dG8xssUzlfsGUVTF1P39qmBvFsg(Unknown Source:0)
E/AndroidRuntime( 9810): 	at com.oppwa.mobile.connect.checkout.dialog.BaseActivity$$ExternalSyntheticLambda4.onFragmentResult(Unknown Source:2)
E/AndroidRuntime( 9810): 	at androidx.fragment.app.FragmentManager$LifecycleAwareResultListener.onFragmentResult(FragmentManager.java:256)
E/AndroidRuntime( 9810): 	at androidx.fragment.app.FragmentManager.setFragmentResult(FragmentManager.java:865)
E/AndroidRuntime( 9810): 	at com.oppwa.mobile.connect.checkout.dialog.PaymentInfoFragment.c(PaymentInfoFragment.java:9)
E/AndroidRuntime( 9810): 	at com.oppwa.mobile.connect.checkout.dialog.PaymentInfoFragment.$r8$lambda$ibu7f8RjDc_YqgendOdUAZ6Kjyg(Unknown Source:0)
E/AndroidRuntime( 9810): 	at com.oppwa.mobile.connect.checkout.dialog.PaymentInfoFragment$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
E/AndroidRuntime( 9810): 	at android.view.View.performClick(View.java:7740)
E/AndroidRuntime( 9810): 	at android.view.View.performClickInternal(View.java:7710)
E/AndroidRuntime( 9810): 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
E/AndroidRuntime( 9810): 	at android.view.View$PerformClick.run(View.java:30629)
E/AndroidRuntime( 9810): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime( 9810): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 9810): 	at android.os.Looper.loopOnce(Looper.java:257)
E/AndroidRuntime( 9810): 	at android.os.Looper.loop(Looper.java:368)
E/AndroidRuntime( 9810): 	at android.app.ActivityThread.main(ActivityThread.java:8839)
E/AndroidRuntime( 9810): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9810): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
E/AndroidRuntime( 9810): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by ahmedelkhyary** [comment]
@SaurabhAlmighty  can you try this example on your phone 

https://github.com/ahmedelkhyary/hyperpay/tree/main/example

**Comment by ahmedelkhyary** [comment]
https://discord.com/invite/T8TyGxpGBS

**Comment by SaurabhAlmighty** [comment]
same problem occurs i have upgrade the version of 3.0.0 and you given git repo with same problem app creashed

**Comment by SaurabhAlmighty** [comment]
In file, android/app/build.gradle change 33 to 34 this line:
targetSdkVersion 33

**Comment by ahmedelkhyary** [comment]
> In file, android/app/build.gradle change 33 to 34 this line: targetSdkVersion 33

upload your demo in repo and i will check it

**Comment by ahmedelkhyary** [comment]
https://github.com/ahmedelkhyary/hyperpay/issues/25
https://github.com/flutter/flutter/issues/133667

based on this issue , I can not update android SDK because there is issue in flutter SDK with native code

**Comment by ahmedelkhyary** [comment]
please check new version 3.1.1
